export const FETCH_CURRENCIES = 'FETCH_CURRENCIES';
export const LOADING_FETCH_CURRENCIES = 'LOADING_FETCH_CURRENCIES';
export const FETCH_CRYPTO_CURRENCIES = 'FETCH_CRYPTO_CURRENCIES';
export const LOADING_FETCH_CRYPTO_CURRENCIES = 'LOADING_FETCH_CRYPTO_CURRENCIES';