import { Dimensions } from 'react-native';
export const BG_APP = '#fff';
export const TEXT_COLOR_APP = '#4B545A';
export const COLOR_APP = '#1152FD';
export const REGULAR = 'Roboto-Regular';
export const MEDIUM = 'Roboto-Medium';
export const BOLD = 'Roboto-Bold';
export const RADIUS_BTN = 15;
export const FULL_WIDTH = Dimensions.get('screen').width;
export const FULL_HEIGHT = Dimensions.get('screen').height;
export const FLEX_CENTER = { alignItems: 'center', justifyContent: 'center' };